name: run bot

on:
  schedule:
    - cron: 0 11 * * *
  workflow_dispatch:
    inputs:
    
jobs:
  sync:
    runs-on: ubuntu-latest
    name: fclonebot
    steps:
      - uses: actions/checkout@v2
      - name: Bot Install1
        run: |
          git clone https://github.com/crypt-bphc/Fclone_Tg_Bot
          cd Fclone_Tg_Bot
          pip3 install -r requirements.txt
          cat >  telegram_gcloner/config.ini  << EOF
          ${{ secrets.BOT_CONFIG }}
          EOF
          sudo chmod +x fclone
          sudo chmod +x telegram_gcloner/telegram_gcloner.py
          sudo python3 telegram_gcloner/telegram_gcloner.py
